@server = https://frankjrr31-psychic-waffle-wwjjjv5xg7r3g7qv-8080.preview.app.github.dev
@instumentos = {{server}}/api/instrumentos
###
GET {{instumentos}}
###
POST {{instumentos}}
Content-Type: application/json

{
    "nombre": "Quena",
    "categoria": "Viento",
    "descripcion": "Tubo de madera con orificios"
}